### ISSUE TITLE
Question on the result

### ISSUE THREAD

**Issue by junhyeokahn** [aakhundov/tf-example-models#2]
How do you actually get a result shown in gmm-best.png. I mean, among several algorithms, which one did you use to get the best result. By just running your codes (e.g. tf_gmm_diag.py, tf_gmm_full.py, tf_gmm_grad, tf_gmm.py), they mostly give incomplete result as below.
<img width="636" alt="screen shot 2018-03-23 at 9 28 35 am" src="https://user-images.githubusercontent.com/23005104/37834802-9f46aa4e-2e7c-11e8-898b-258cfa044de6.png">
Is gmm sensitive to initial mean assignment?

**Comment by aakhundov** [comment]
Hello,

Sorry for the late answer, I somehow missed your question.

GMM (as well as K-Means) is indeed quite sensitive to initial mean assignments. So, if the initial mean values don't cover all the clusters in the data, t's quite hard for the algorithm to properly reassign them. What people frequently do in practice to circumvent this is finding the initial mean assignment using cheaper K-Means, and then running an EM to train a GMM (see Bishop's "PRML", page 438).

The results shown in the "gmm-best.png" (as well as "kmeans-best.png") are *the best* results obtained from a series of tf_gmm.py (and tf_kmeans.py) runs (which is kind of manifested in the file names :)).

Hope this helps!
